### ISSUE TITLE
Icon updates - DoubleCheckIcon is missing in Icons

### ISSUE THREAD

**Issue by manojx031** [xola/ui-kit#142] opened 2022-07-19 08:53 UTC
Double Check Icon from Product Pricing is missing in UI Kit. 

https://www.figma.com/file/pcffxLuMluqCsBQYAWG9sp/04-Product?node-id=5405%3A226384

**Comment by rushi** [comment] 2022-07-29 06:28
`Stars.svg` needs to be copied. There is another `FlexFeeIcon` created by design and we need to find out where that needs to be used

**Comment by rushi** [comment] 2022-07-29 06:28
Add these from Sachin

![image](https://user-images.githubusercontent.com/65708/181696916-8ef4d7f5-f6ff-4fcb-81f5-70fad61e5296.png)

**Comment by rushi** [comment] 2022-08-05 05:07
Dropdown icon 
<img width="808" alt="CleanShot 2022-08-05 at 10 37 02@2x" src="https://user-images.githubusercontent.com/65708/183005600-96d75cad-50c0-4db8-9304-9f7fb40a6c46.png">
 
https://www.figma.com/file/pcffxLuMluqCsBQYAWG9sp/04-Product?node-id=1149:149792

**Comment by rushi** [comment] 2022-08-05 05:10
Add tag of "bulb" to 
<img width="560" alt="image" src="https://user-images.githubusercontent.com/65708/183005745-01ce189d-5bca-4d9f-9433-d3ec3d6757c0.png">

**Comment by rushi** [comment] 2022-09-12 06:43
Closed by the merge of https://github.com/xola/ui-kit/pull/181

**Closed by rushi** 2022-09-12 06:43 UTC
Labels: bug
